name: Deploy Landing (multi-domínio) — arquivar + build + publicar

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Domínio'
        type: choice
        options: [pinacle.com.br, gestordecapitais.com]
        required: true
      slug:
        description: 'Slug (ex: vendaimovel)'
        required: true
      kind:
        description: 'Tipo de fonte'
        type: choice
        # Mantenho vite_git só para compat; os passos abaixo ignoram vite.
        options: [zip_repo, zip_url, flutter_git, vite_git]
        required: true
      # para *_git
      repo:
        description: 'owner/name do projeto (para *_git)'
        required: false
      ref:
        description: 'branch/tag (para *_git)'
        default: 'main'
        required: false
      subdir:
        description: 'Subpasta no repo (para *_git)'
        default: ''
        required: false
      # para zip_url
      zip_url:
        description: 'URL pública do ZIP (para zip_url; conter projeto Flutter)'
        required: false
      # para zip_repo
      zip_path:
        description: 'Caminho do ZIP dentro deste repo (para zip_repo), ex: uploads/meu-app.zip'
        required: false

permissions:
  contents: write

concurrency:
  group: deploy-landing
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ARCHIVE_ROOT: catalog

    steps:
      - name: Checkout (repo ops)
        uses: actions/checkout@v4

      - name: Validar & checar servidor
        run: |
          [[ "${{ github.event.inputs.slug }}" =~ ^[a-z0-9-]{1,64}$ ]] || { echo "Slug inválido. Use [a-z0-9-]"; exit 1; }
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p "${{ secrets.SSH_PORT || 22 }}" -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa -p "${{ secrets.SSH_PORT || 22 }}" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "[ -d /var/www/pages/${{ github.event.inputs.domain }} ] || { echo 'Domínio não preparado no servidor'; exit 1; }"

      # ===== Fontes GIT =====
      - name: Checkout fonte (GIT)
        if: ${{ startsWith(github.event.inputs.kind, 'flutter_') }}
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo || github.repository }}
          ref: ${{ github.event.inputs.ref }}
          path: _src

      - name: Definir paths (com fallback)
        if: ${{ startsWith(github.event.inputs.kind, 'flutter_') }}
        run: |
          REQ="${{ github.event.inputs.subdir || '.' }}"
          CAND="_src/$REQ"
          if [ ! -d "$CAND" ]; then
            echo "SUBDIR=." >> $GITHUB_ENV
            echo "PATH_SRC=_src" >> $GITHUB_ENV
            echo "Aviso: subdir '$REQ' não encontrado; usando raiz do repo."
          else
            echo "SUBDIR=$REQ" >> $GITHUB_ENV
            echo "PATH_SRC=$CAND" >> $GITHUB_ENV
          fi

      # ===== Fonte ZIP (URL) =====
      - name: Obter ZIP (zip_url)
        if: ${{ github.event.inputs.kind == 'zip_url' }}
        run: |
          curl -L "${{ github.event.inputs.zip_url }}" -o site.zip

      # ===== Fonte ZIP (repo) =====
      - name: Obter ZIP (zip_repo)
        if: ${{ github.event.inputs.kind == 'zip_repo' }}
        run: |
          ZIP="${{ github.event.inputs.zip_path }}"
          [ -n "$ZIP" ] || { echo "zip_path obrigatório para zip_repo"; exit 1; }
          case "$ZIP" in
            /*|*..*) echo "zip_path inválido (não usar / absoluto ou ..)"; exit 1;;
          esac
          [ -f "$ZIP" ] || { echo "Arquivo não encontrado: $ZIP"; exit 1; }
          cp "$ZIP" site.zip

      # ===== Preparar fonte ZIP como Flutter Web (sempre) =====
      - name: Descompactar ZIP para _src (Flutter)
        if: ${{ github.event.inputs.kind == 'zip_repo' || github.event.inputs.kind == 'zip_url' }}
        run: |
          rm -rf _src && mkdir -p _src
          unzip -o site.zip -d _src
          test -f _src/pubspec.yaml || { echo "pubspec.yaml não encontrado no ZIP (esperado projeto Flutter)"; exit 1; }
          echo "PATH_SRC=_src" >> $GITHUB_ENV

      # ===== Cache do Flutter (acelera builds) =====
      - name: Cache pub (Flutter)
        if: ${{ github.event.inputs.kind == 'zip_repo' || github.event.inputs.kind == 'zip_url' || github.event.inputs.kind == 'flutter_git' }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ${{ env.PATH_SRC }}/.dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles(env.PATH_SRC + '/pubspec.lock', env.PATH_SRC + '/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      # ===== Setup Flutter =====
      - name: Setup Flutter
        if: ${{ github.event.inputs.kind == 'zip_repo' || github.event.inputs.kind == 'zip_url' || github.event.inputs.kind == 'flutter_git' }}
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # ===== Build Flutter Web (ZIP) =====
      - name: Build Flutter Web (ZIP)
        if: ${{ github.event.inputs.kind == 'zip_repo' || github.event.inputs.kind == 'zip_url' }}
        working-directory: ${{ env.PATH_SRC }}
        run: |
          set -e
          flutter --version
          flutter clean
          flutter config --enable-web
          flutter pub get
          if flutter build web -h | grep -q -- '--web-renderer'; then
            flutter build web --release --web-renderer canvaskit \
              --base-href /p/${{ github.event.inputs.slug }}/
          else
            flutter build web --release \
              --base-href /p/${{ github.event.inputs.slug }}/
          fi
          echo "DIST=${PWD}/build/web" >> $GITHUB_ENV

      # ===== Build Flutter Web (GIT) =====
      - name: Build Flutter Web (GIT)
        if: ${{ github.event.inputs.kind == 'flutter_git' }}
        working-directory: ${{ env.PATH_SRC }}
        run: |
          set -e
          flutter --version
          flutter clean
          flutter config --enable-web
          flutter pub get
          if flutter build web -h | grep -q -- '--web-renderer'; then
            flutter build web --release --web-renderer canvaskit \
              --base-href /p/${{ github.event.inputs.slug }}/
          else
            flutter build web --release \
              --base-href /p/${{ github.event.inputs.slug }}/
          fi
          echo "DIST=${PWD}/build/web" >> $GITHUB_ENV

      # ===== Arquivar a fonte no repo ops =====
      - name: Arquivar fonte (zip ou git)
        run: |
          TS=$(date +%Y%m%d-%H%M%S)
          DEST="$ARCHIVE_ROOT/${{ github.event.inputs.domain }}/${{ github.event.inputs.slug }}"
          mkdir -p "$DEST"
          if [[ "${{ github.event.inputs.kind }}" == zip_url || "${{ github.event.inputs.kind }}" == zip_repo ]]; then
            cp site.zip "$DEST/source-$TS.zip"
            if [[ "${{ github.event.inputs.kind }}" == zip_url ]]; then
              SRCINFO="zip_url=${{ github.event.inputs.zip_url }}"
            else
              SRCINFO="zip_repo=${{ github.event.inputs.zip_path }}"
            fi
          else
            (cd "$PATH_SRC" && zip -qr "$GITHUB_WORKSPACE/$DEST/source-$TS.zip" .)
            SRCINFO="repo=${{ github.event.inputs.repo || github.repository }}, ref=${{ github.event.inputs.ref }}, subdir=${{ github.event.inputs.subdir || '.' }}"
          fi
          cat > "$DEST/meta.json" <<META
          { "domain": "${{ github.event.inputs.domain }}",
            "slug":   "${{ github.event.inputs.slug }}",
            "kind":   "${{ github.event.inputs.kind }}",
            "source": "${SRCINFO}",
            "run_id": "${{ github.run_id }}",
            "commit": "${{ github.sha }}",
            "archived_at": "$TS" }
          META
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$DEST"
          git commit -m "archive: ${{ github.event.inputs.domain }}/p/${{ github.event.inputs.slug }} [skip ci]" || true
          git push || true

      # ===== Deploy =====
      - name: Rsync pro servidor
        run: |
          rsync -avzr --delete \
            -e "ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT || 22 }}" \
            "$DIST"/ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/pages/${{ github.event.inputs.domain }}/${{ github.event.inputs.slug }}/

      - name: Gravar version.txt no destino
        run: |
          ssh -i ~/.ssh/id_rsa -p "${{ secrets.SSH_PORT || 22 }}" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "printf 'domain=%s\nslug=%s\nkind=%s\ncommit=%s\nrun_id=%s\ndate=%s\n' \
             '${{ github.event.inputs.domain }}' '${{ github.event.inputs.slug }}' '${{ github.event.inputs.kind }}' \
             '${{ github.sha }}' '${{ github.run_id }}' \"\$(date -u +'%F %T UTC')\" \
             > /var/www/pages/${{ github.event.inputs.domain }}/${{ github.event.inputs.slug }}/version.txt"
